// lib/habitData.ts
export const allHabits = [
  'Do at least 30 minutes of physical activity each day',
  'Eat fruits and vegetables every day',
  'Go to bed by 11:00 PM',
  'Sleep at least 8 hours per night',
  'Meditate for 5–10 minutes every morning or evening',
  'Reduce time spent on social media',
  'Walk at least 4,000 steps a day',
  'Do 10 minutes of morning stretching',
  'Quit smoking',
  'Don’t work after 8:00 PM and avoid checking email on weekends',
  'Remember to drink enough water',
  'Use a reusable water bottle',
  'Read for at least 30 minutes a day',
  'Spend at least 30 minutes a day on a hobby',
  'Call friends or family at least once a week',
  'Follow a morning routine',
  'Follow an evening routine',
  'Write in a gratitude journal once a day',
  'Track your income and expenses',
  'Read one professional article a day',
  'Post one helpful cast every day',
  'Keep a daily emotion journal',
  'Use the 2-minute rule for quick tasks',
  'Learn 5–10 new words of a foreign language daily',
  'Plan your day the night before',
  'Set 3 key tasks for the day',
  'Use the Pomodoro method — 25 min focus + 5 min break',
  'Put your phone in focus mode while working',
  'Keep a to-do list and check off completed items',
  'Avoid checking your phone right after waking up',
];
