export const quotes = [
    { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { quote: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
    { quote: "It is never too late to be what you might have been.", author: "George Eliot" },
    { quote: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
    { quote: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
    { quote: "Creativity takes courage.", author: "Henri Matisse" },
    { quote: "You can’t use up creativity. The more you use, the more you have.", author: "Maya Angelou" },
    { quote: "I have not failed. I’ve just found 10,000 ways that won’t work.", author: "Thomas Edison" },
    { quote: "Your time is limited, so don’t waste it living someone else’s life.", author: "Steve Jobs" },
    { quote: "What you seek is seeking you.", author: "Rumi" },
    { quote: "It’s kind of fun to do the impossible.", author: "Walt Disney" },
    { quote: "To live a creative life, we must lose our fear of being wrong.", author: "Joseph Chilton Pearce" },
    { quote: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
    { quote: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
    { quote: "Every artist was first an amateur.", author: "Ralph Waldo Emerson" },
    { quote: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
    { quote: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
    { quote: "Art washes away from the soul the dust of everyday life.", author: "Pablo Picasso" },
    { quote: "Don’t wait. The time will never be just right.", author: "Napoleon Hill" },
    { quote: "If you can’t explain it simply, you don’t understand it well enough.", author: "Albert Einstein" },
    { quote: "The best way out is always through.", author: "Robert Frost" },
    { quote: "Write hard and clear about what hurts.", author: "Ernest Hemingway" },
    { quote: "Imagination is more important than knowledge.", author: "Albert Einstein" },
    { quote: "The scariest moment is always just before you start.", author: "Stephen King" },
    { quote: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
    { quote: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
    { quote: "Done is better than perfect.", author: "Sheryl Sandberg" },
    { quote: "Stay hungry, stay foolish.", author: "Stewart Brand" },
    { quote: "The purpose of life is to find your gift. The meaning of life is to give it away.", author: "Pablo Picasso" },
    { quote: "There is no innovation and creativity without failure.", author: "Brené Brown" },
    { quote: "Normality is a paved road. It’s comfortable to walk, but no flowers grow on it.", author: "Vincent van Gogh" },
    { quote: "Logic will get you from A to B. Imagination will take you everywhere.", author: "Albert Einstein" },
    { quote: "You don’t find the happy life. You make it.", author: "Camilla Eyring Kimball" },
    { quote: "Work hard in silence, let success be your noise.", author: "Frank Ocean" },
    { quote: "Make visible what, without you, might never have been seen.", author: "Robert Bresson" },
    { quote: "Creativity is intelligence having fun.", author: "Albert Einstein" },
    { quote: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { quote: "People will forget what you said, but they will never forget how you made them feel.", author: "Maya Angelou" },
    { quote: "There is nothing noble in being superior to your fellow man; true nobility is being superior to your former self.", author: "Ernest Hemingway" },
    { quote: "Passion is energy. Feel the power that comes from focusing on what excites you.", author: "Oprah Winfrey" },
    { quote: "Every great dream begins with a dreamer.", author: "Harriet Tubman" },
    { quote: "If you hear a voice within you say ‘you cannot paint,’ then by all means paint, and that voice will be silenced.", author: "Vincent van Gogh" },
    { quote: "The best way to predict the future is to invent it.", author: "Alan Kay" },
    { quote: "Success is liking yourself, liking what you do, and liking how you do it.", author: "Maya Angelou" },
    { quote: "An essential aspect of creativity is not being afraid to fail.", author: "Edwin Land" },
    { quote: "Don’t bunt. Aim out of the ballpark.", author: "David Ogilvy" },
    { quote: "The world always seems brighter when you’ve just made something that wasn’t there before.", author: "Neil Gaiman" },
    { quote: "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett" },
    { quote: "Art is not freedom from discipline, but disciplined freedom.", author: "John F. Kennedy Jr." },
    { quote: "Inspiration exists, but it has to find you working.", author: "Pablo Picasso" }
  ];
  